# Generated by Django 5.1.4 on 2025-04-06 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0007_alter_devis_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='cout_backend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='devis',
            name='cout_frontend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
