# Generated by Django 5.1.4 on 2025-04-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0008_alter_devis_cout_backend_alter_devis_cout_frontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='validite',
            field=models.IntegerField(default=10, help_text='en jours'),
        ),
    ]
