# Generated by Django 5.1.4 on 2025-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0010_remove_facture_fichier_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='invoice_type',
        ),
        migrations.AddField(
            model_name='facture',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
    ]
