# Generated by Django 5.1.4 on 2025-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Service', '0011_remove_facture_invoice_type_facture_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='validite',
            field=models.IntegerField(default=10, help_text='en jours'),
        ),
    ]
